WIP Bump click to 22.1.0
globality-corp/globality-black pull request #23
Opened 2022-03-28 17:33 UTC by sstrasser-globality

_Short description of the change and what it should accomplish_

Closes [GLOB-xxxxx]

2022-03-28 18:36 UTC, marcglobality reviewed
I'm ok with the changes but before approving I would like @uri-miron-globality to review this as well as he brought the tomli pin some PRs ago

2022-03-28 18:51 UTC, sstrasser-globality commented on setup.py
> +        "black>=22.1.0",
Woops. Yah, good call!

2022-03-29 10:49 UTC, uri-miron-globality requested changes

2022-03-29 10:49 UTC, uri-miron-globality commented on setup.py
> +        "black>=22.1.0",
Yes, I investigated this awhile back. The issue is that marquez is pinning flask<2, which pins click<8, which conflicts with black>=22. The solution is for marquez to update requirements... Until this is done, the only way I could build a repo that uses both globality-black and marquez was to pin both black and click in this file.

2023-01-20 11:06 UTC, marcglobality commented on setup.py
> +        "black>=22.1.0",
> please leave pinned. If you want, to 22.1.0. But we don't want black to suddenly change into something that makes all our CIs to start failing

I'm going to contradict myself and say that if better to break CIs than being stuck in old requirements. So as long as we fix the issues brought up by @uri-miron-globality , let's do this

2023-01-20 15:22 UTC, sstrasser-globality commented on setup.py
> +        "black>=22.1.0",
I think you already fixed this issue here: https://github.com/globality-corp/marquez/pull/3814/files? So we should be able to roll this forward with almost minimal impact.

2023-01-20 16:34 UTC, tomaszpietruszka-globality approved these changes
LGTM, as long as we can test if with repos of different types (AI, backend service) and it works - lets unpin!

2023-01-22 09:22 UTC, uri-miron-globality approved these changes
LGTM

2023-01-23 20:29 UTC, merged